# Generated by Django 3.0.5 on 2020-04-11 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200411_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 7, 30, 18, 685492, tzinfo=utc)),
        ),
    ]
